# Generated by Django 3.2.13 on 2022-05-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productweight',
            name='weight',
            field=models.CharField(max_length=255, verbose_name='Вес'),
        ),
    ]
