# Generated by Django 3.2.13 on 2022-05-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productweight_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'шт'), ('kg', 'кг'), ('liter', 'литр')], default='piece', max_length=255, verbose_name='Ед.изм'),
            preserve_default=False,
        ),
    ]
