# Generated by Django 3.2.13 on 2022-05-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productweight',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
