# Generated by Django 3.2.13 on 2022-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
