# Generated by Django 3.2.13 on 2022-04-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('unit', models.CharField(choices=[('piece', 'шт'), ('kg', 'кг'), ('liter', 'литр')], max_length=255, verbose_name='Ед.изм')),
                ('total', models.FloatField(verbose_name='Общая сумма')),
                ('status', models.CharField(choices=[('ready', 'На складе'), ('progress', 'Используется'), ('finished', 'Закончен')], default='ready', max_length=255, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Сырье',
                'verbose_name_plural': 'Сырье',
            },
        ),
        migrations.CreateModel(
            name='WarehouseRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Кол-во')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.raw', verbose_name='Сырье')),
            ],
            options={
                'verbose_name': 'Сырье в складе',
                'verbose_name_plural': 'Сырье в складе',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Кол-во')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Продукт в складе',
                'verbose_name_plural': 'Продукты в складе',
            },
        ),
    ]
