# Generated by Django 3.2.13 on 2022-05-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('warehouse', '0002_warehouseproduct_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='product_weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productweight', verbose_name='Вес/Размер товара'),
        ),
    ]
