# Generated by Django 3.2.13 on 2022-05-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_income_incomeproductitem_incomerawitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='raw',
            name='total',
        ),
    ]
