# Generated by Django 3.2.13 on 2022-05-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_raw_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw',
            name='price',
        ),
    ]
