# Generated by Django 3.2.13 on 2022-05-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_raw_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeproductitem',
            name='income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.income', verbose_name='Приход'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomerawitem',
            name='income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.income', verbose_name='Приход'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.FloatField(default=0, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('deactive', 'Не активный')], default='active', max_length=255, verbose_name='Статус'),
        ),
    ]
