# Generated by Django 3.2.13 on 2022-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20220525_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
