# Generated by Django 3.2.13 on 2022-05-25 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_unit'),
        ('warehouse', '0009_auto_20220525_1647'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(default=0, verbose_name='Общяя сумма')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('accepted', 'Принято'), ('canceled', 'Отменено')], default='created', max_length=255, verbose_name='Статус')),
                ('warehouse_type', models.CharField(choices=[('product', 'Продуктовый'), ('raw', 'Сырьевой')], max_length=255, verbose_name='Тип склада')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
        migrations.CreateModel(
            name='IncomeRawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Кол-во')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('total', models.FloatField(verbose_name='Общая сумма')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.income', verbose_name='Приход')),
                ('raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.raw', verbose_name='Сырье')),
            ],
            options={
                'verbose_name': 'Приход сырья',
                'verbose_name_plural': 'Приходы сырья',
            },
        ),
        migrations.CreateModel(
            name='IncomeProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Кол-во')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('total', models.FloatField(verbose_name='Общая сумма')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.income', verbose_name='Приход')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
                ('product_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolor', verbose_name='Цвет товара')),
                ('product_weight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productweight', verbose_name='Вес/Размер товара')),
            ],
            options={
                'verbose_name': 'Приход продукции',
                'verbose_name_plural': 'Приходы продукции',
            },
        ),
    ]
