# Generated by Django 3.2.13 on 2022-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_incomeproductitem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerawitem',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
