# Generated by Django 3.2.13 on 2022-04-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatar/', verbose_name='Фото профиля')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='user_passport_photo/', verbose_name='Фото пасспорта')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Имя пользователя')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес прописки')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('birth_day', models.DateField(blank=True, max_length=255, null=True, verbose_name='Дата рождение')),
                ('user_type', models.CharField(choices=[('agent', 'Агент'), ('raw_warehouse_manager', 'Зав сырьевой склад'), ('finished_products_warehouse_manager', 'Зав склада готовой продукции'), ('director', 'Директор')], max_length=255, verbose_name='Тип пользователя')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
