# Generated by Django 3.2.13 on 2022-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Зарплата'),
        ),
    ]
