# Generated by Django 3.2.13 on 2022-05-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productcategory_title'),
        ('order', '0002_order_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productcolor', verbose_name='Цвет товара'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productweight', verbose_name='Вес товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('pending', 'В ожидании'), ('accepted', 'Принято'), ('sent', 'Отправлено'), ('canceled', 'Отменено')], default='created', max_length=255, verbose_name='Статус'),
        ),
    ]
