# Generated by Django 3.2.13 on 2022-05-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
