# Generated by Django 3.2.13 on 2022-06-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money_type',
            field=models.CharField(choices=[('cash', 'Нахт'), ('duty', 'Долг')], max_length=255, null=True, verbose_name='Тип платежа'),
        ),
    ]
